baseURL = "//uncleverlabs.com"
title   = "Unclever Labs"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "../public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Unclever Labs"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "A Collective of Lazy Developers"
  keywords = ""
  images = [""]

  homeTitle = "A Collective of Lazy Developers"
  homeSubtitle = "Bright people who don't overcomplicate things"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  [params.logo]
    # logoText     = "$ cd /home/"
    logoText     = "Unclever Labs"
    logoHomeLink = "/"

  # Social icons
  # [[params.social]]
  #   name = "twitter"
  #   url  = "https://twitter.com/"

  # [[params.social]]
  #   name = "email"
  #   url  = "mailto:nobody@example.com"

  # [[params.social]]
  #   name = "github"
  #   url  = "https://github.com/rms1000watt"

  # [[params.social]]
  #   name = "linkedin"
  #   url  = "https://www.linkedin.com/in/ryanmatthewsmith"

  [[params.people]]
    name = "Mike Cherry"
    title = "Software"
    photoURL = "https://media.licdn.com/dms/image/C4E03AQHMCsi4HmXJAA/profile-displayphoto-shrink_800_800/0?e=1565222400&v=beta&t=8E4EqR6FIidnbSI2qm_yY4a0_DEDqshtisBd7Ad9FEs"
    linkedin = "mikec2"
  [[params.people]]
    name = "Chris Stobie"
    title = "DevOps"
    photoURL = "https://media.licdn.com/dms/image/C5603AQFuZKevEYkaoA/profile-displayphoto-shrink_800_800/0?e=1565222400&v=beta&t=HFt59sJOcmar9g_EXUZWfrZjCMcCR21mC6mMsdLcBWk"
    linkedin = "cstobie"
    github = "lanmalkieri"
  [[params.people]]
    name = "Jonathan Tobe"
    title = "Software"
    photoURL = "https://media.licdn.com/dms/image/C4D03AQF8mVU7wu6dsQ/profile-displayphoto-shrink_800_800/0?e=1565222400&v=beta&t=ur1JpeKfReQWxMPfy_cAeEMDbSauXBwOY2ry5Rk25K8"
    linkedin = "jonathan-tobe-76a50819"
  [[params.people]]
    name = "Ryan Smith"
    title = "DevOps"
    gravatarHash = "26e059f135386262f6c4bb3c90de1027"
    linkedin = "ryanmatthewsmith"
    github = "rms1000watt"
  [[params.people]]
    name = "Justin King"
    title = "DevOps"
    photoURL = "https://media.licdn.com/dms/image/C4D03AQEPhVcFD4wQ-g/profile-displayphoto-shrink_800_800/0?e=1565222400&v=beta&t=cx_lPcKaifO_u7NL8NzqF7FWi3yE6YC9CzZYjgWNyO8"
    linkedin = "justin-king-26a4081b"
  [[params.people]]
    name = "Andy McIntosh"
    title = "Product"
    photoURL = "https://pbs.twimg.com/profile_images/1967113482/Ink-meNEWa_200x200.png"
    linkedin = "andrew-mcintosh-6079324a"
    twitter = "andymmmmc"
  [[params.people]]
    name = "Blake Melcher"
    title = "IT Eng"
    photoURL = "https://media.licdn.com/dms/image/C5603AQH_FsRxQE3pVQ/profile-displayphoto-shrink_800_800/0?e=1565222400&v=beta&t=l7irkrF1Wri_vkT68uVNH4NATDXRJuSKW_yEBDBKhKg"
    linkedin = "blakemelcher"
  [[params.people]]
    name = "TODO: F R"
  [[params.people]]
    name = "TODO: R P"
  [[params.people]]
    name = "Chad Thomas"
    title = "Mentorship"
    photoURL = "https://media.licdn.com/dms/image/C4E03AQElAVqncEIyHA/profile-displayphoto-shrink_800_800/0?e=1565222400&v=beta&t=K59VUzPipCTaHKrNpUXm5rm7ddlOHfXB7Xo6-4U5O28"
    linkedin = "iamchad"
  [[params.people]]
    name = "TODO: M M"
  [[params.people]]
    name = "Chase Ward"
    title = "Data"
    photoURL = "https://media.licdn.com/dms/image/C4E03AQFay3wrEcUWKg/profile-displayphoto-shrink_800_800/0?e=1565827200&v=beta&t=aUE6eHxxTQUtH4J5lLr_nRzY_hnynCL1qVjOE677fek"
    linkedin = "chase-ward-34b54689"
  [[params.people]]
    name = "Mark Marcantano"
    title = "DevOps/SCRUM"
    photoURL = "https://media.licdn.com/dms/image/C4D03AQFT4Zsa4KPp5Q/profile-displayphoto-shrink_800_800/0?e=1565827200&v=beta&t=1yqRJdKbkYQ09nczvB4iopU_luRNxGEttwkyr6M7Jz4"
    linkedin = "markthomasm"

  [[params.build]]
    name = "Serverless TF"
    description = "Serverless framework in Terraform"
    github = "github.com/rms1000watt/serverless-tf"

[languages]
  [languages.en]
    subtitle  = "A Collective of Lazy Developers"
    # weight    = 1
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 1
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
    weight     = 2
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = 3
