baseURL = "//uncleverlabs.com"
title   = "A Collective of Lazy Developers"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "../public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Unclever Labs"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Unclever Labs: A Collective of Lazy Developers"
  keywords = ""
  images = [""]

  homeSubtitle = "Bright people who don't overcomplicate things"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  [params.logo]
    # logoText     = "$ cd /home/"
    logoText     = "Unclever Labs"
    logoHomeLink = "/"

  # Social icons
  # [[params.social]]
  #   name = "twitter"
  #   url  = "https://twitter.com/"

  # [[params.social]]
  #   name = "email"
  #   url  = "mailto:nobody@example.com"

  # [[params.social]]
  #   name = "github"
  #   url  = "https://github.com/rms1000watt"

  # [[params.social]]
  #   name = "linkedin"
  #   url  = "https://www.linkedin.com/in/ryanmatthewsmith"

  [[params.people]]
    name = "todo"

  [[params.people]]
    name = "todo"
  [[params.people]]
    name = "todo"
  [[params.people]]
    name = "todo"
  [[params.people]]
    name = "todo"
  [[params.people]]
    name = "todo"

  [[params.build]]
    name = "Serverless TF"
    description = "Serverless framework in Terraform"
    github = "github.com/rms1000watt/serverless-tf"

[languages]
  [languages.en]
    subtitle  = "Unclever Labs: A Collective of Lazy Developers"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 1
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
    weight     = 2
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = 3
